import { Property } from "./models";

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Modern Apartment in Downtown",
    description:
      "Beautiful modern apartment with all amenities in the heart of the city.",
    price: 120,
    priceType: "night",
    location: "New York, NY",
    images: [
      "/images/property1.jpg",
      "/images/property1-2.jpg",
      "/images/property1-3.jpg",
    ],
    rating: 4.8,
    reviews: 124,
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Washer", "TV", "Pool"],
    propertyType: "Apartment",
    hostName: "Sarah Johnson",
    hostImage: "/images/host1.jpg",
    available: true,
    featured: true,
  },
  {
    id: "2",
    title: "Cozy Beach House with Ocean View",
    description:
      "Relax in this beautiful beach house with stunning ocean views and private access to the beach.",
    price: 250,
    priceType: "night",
    location: "Miami Beach, FL",
    images: [
      "/images/property2.jpg",
      "/images/property2-2.jpg",
      "/images/property2-3.jpg",
    ],
    rating: 4.9,
    reviews: 87,
    bedrooms: 3,
    bathrooms: 2,
    area: 1200,
    amenities: [
      "WiFi",
      "Air conditioning",
      "Kitchen",
      "Beach access",
      "Balcony",
      "Parking",
    ],
    propertyType: "House",
    hostName: "Michael Brown",
    hostImage: "/images/host2.jpg",
    available: true,
    featured: true,
  },
  {
    id: "3",
    title: "Luxury Penthouse with City Views",
    description:
      "Stunning penthouse apartment with panoramic city views, modern amenities, and rooftop terrace.",
    price: 350,
    priceType: "night",
    location: "Los Angeles, CA",
    images: [
      "/images/property3.jpg",
      "/images/property3-2.jpg",
      "/images/property3-3.jpg",
    ],
    rating: 4.7,
    reviews: 56,
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    amenities: [
      "WiFi",
      "Air conditioning",
      "Kitchen",
      "Gym",
      "Pool",
      "Parking",
      "Doorman",
    ],
    propertyType: "Penthouse",
    hostName: "Jennifer Davis",
    hostImage: "/images/host3.jpg",
    available: true,
    featured: true,
  },
  {
    id: "4",
    title: "Charming Studio in Historic District",
    description:
      "Cozy studio apartment in a historic building with character and charm, walking distance to attractions.",
    price: 80,
    priceType: "night",
    location: "Boston, MA",
    images: ["/images/property4.jpg", "/images/property4-2.jpg"],
    rating: 4.5,
    reviews: 42,
    bedrooms: 1,
    bathrooms: 1,
    area: 500,
    amenities: ["WiFi", "Kitchen", "Heating", "TV", "Washer"],
    propertyType: "Studio",
    hostName: "David Wilson",
    hostImage: "/images/host4.jpg",
    available: true,
  },
  {
    id: "5",
    title: "Mountain Cabin Retreat",
    description:
      "Escape to this peaceful cabin surrounded by nature with hiking trails nearby.",
    price: 150,
    priceType: "night",
    location: "Aspen, CO",
    images: [
      "/images/property5.jpg",
      "/images/property5-2.jpg",
      "/images/property5-3.jpg",
    ],
    rating: 4.9,
    reviews: 76,
    bedrooms: 2,
    bathrooms: 1,
    area: 900,
    amenities: [
      "WiFi",
      "Fireplace",
      "Kitchen",
      "Mountain view",
      "Parking",
      "Heating",
    ],
    propertyType: "Cabin",
    hostName: "Amanda Miller",
    hostImage: "/images/host5.jpg",
    available: true,
    featured: true,
  },
  {
    id: "6",
    title: "Contemporary Loft in Arts District",
    description:
      "Stylish loft in the vibrant arts district with high ceilings and industrial charm.",
    price: 180,
    priceType: "night",
    location: "Portland, OR",
    images: ["/images/property6.jpg", "/images/property6-2.jpg"],
    rating: 4.6,
    reviews: 38,
    bedrooms: 1,
    bathrooms: 1,
    area: 850,
    amenities: [
      "WiFi",
      "Air conditioning",
      "Kitchen",
      "Washer",
      "TV",
      "Workspace",
    ],
    propertyType: "Loft",
    hostName: "Robert Thompson",
    hostImage: "/images/host6.jpg",
    available: true,
  },
];
